### ISSUE TITLE
New idea: Renko open and Renko close

### ISSUE THREAD

**Issue by redallica** [quantroom-pro/pyrenko#1]
Hey!

First want to thank you @quantroom-pro @lamres  for this module, because it is tough to find Renko source files in Python.
The get_renko_prices is providing the close price of the renko brick. As an idea, would that be possible to get the open price of the renko bricks and include for them (renko open price and renko close price) the ema with TA-Lib. I think it could be a nice addition to the module.
Cheers,

**Comment by lamres** [comment]
@redallica Thanks for your feedback!
If you need to get open Renko bars you can get close Renko bars and to add/subtract Renko step size (- for green bars, + for red bars). After that, you can pass new open Renko bars into talib.EMA function. Example here:
https://www.programcreek.com/python/example/92322/talib.EMA
