### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by Carbonblack8** [quantroom-pro/pyrenko#3]
I am receiving the following error while using pip install:

Collecting git+https://github.com/quantroom-pro/pyrenko
  Cloning https://github.com/quantroom-pro/pyrenko to /private/var/folders/46/v4776m9n5lqfw0rt2623lhmw0000gp/T/pip-req-build-mwt6iy93
  Running command git clone -q https://github.com/quantroom-pro/pyrenko /private/var/folders/46/v4776m9n5lqfw0rt2623lhmw0000gp/T/pip-req-build-mwt6iy93
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Applications/anaconda/lib/python3.5/tokenize.py", line 454, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/46/v4776m9n5lqfw0rt2623lhmw0000gp/T/pip-req-build-mwt6iy93/setup.py'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/46/v4776m9n5lqfw0rt2623lhmw0000gp/T/pip-req-build-mwt6iy93/

**Comment by lamres** [comment]
Hi.
The package haven't prepared for installing via pip yet. At this moment, you can copy & paste the file contained the class as it demonstrated in the example.

**Comment by jgardezi** [comment]
@lamres can you give an example of how to use pyrenko. When I tried to use `import pyrenko`, I am getting the following error 

> No module named pyrenko.

Any help how import pyrenko or where should I copy & paste the file contained the class as it demonstrated in the example?

I have copy & paste the file pyrenko.py in the same directory and python is still complaining about it.

**Comment by lamres** [comment]
@jgardezi This example located in the repository. The module file (pyrenko.py) should be located in the same directory. In this example, it locates next to the ipynb-file as well. Have you tried to download and run the repo example?
If you code some py-script it should be located to that py-script.

**Comment by jgardezi** [comment]
@lamers thank you I got it working now. I had issue with pycharm and its working now.
