### ISSUE TITLE
AttributeError: module 'matplotlib.pyplot' has no attribute 'clear'

### ISSUE THREAD

**Issue by lamres** [quantroom-pro/pyrenko#4]
trying to run i get 
`Traceback (most recent call last):
  File "historicalrenko.py", line 71, in <module>
    renko_obj_atr.plot_renko()
  File "/home/james/Jamie/iqoption-bot/pyrenko.py", line 146, in plot_renko
    self.ax.clear()
AttributeError: module 'matplotlib.pyplot' has no attribute 'clear'`
any help

_Originally posted by @jamienjoroge in https://github.com/quantroom-pro/pyrenko/issues/2#issuecomment-539487057_

**Comment by antunsz** [comment]
Hello, uncomment the line 145 in pyrenko.py and change the line 146 to "self.ax = ax".

cause the self.ax is initialized as pyplot, but need to be an axes instance.

Another solution is change the line 12 "self.ax = plt" to "_, self.ax = plt.subplots(1, figsize=(20, 10))"

**Comment by antunsz** [comment]
> trying to run i get
> `Traceback (most recent call last): File "historicalrenko.py", line 71, in <module> renko_obj_atr.plot_renko() File "/home/james/Jamie/iqoption-bot/pyrenko.py", line 146, in plot_renko self.ax.clear() AttributeError: module 'matplotlib.pyplot' has no attribute 'clear'`
> any help
> 
> _Originally posted by @jamienjoroge in [#2 (comment)](https://github.com/quantroom-pro/pyrenko/issues/2#issuecomment-539487057)_

Hello, uncomment the line 145 in pyrenko.py and change the line 146 to "self.ax = ax".

cause the self.ax is initialized as pyplot, but need to be an axes instance.

Another solution is change the line 12 "self.ax = plt" to "_, self.ax = plt.subplots(1, figsize=(20, 10))"
