### ISSUE TITLE
In backtests brick size is calculated as if we know the whole history forward. How often brick size should be recalculated in Live trading? Thanks forward!

### ISSUE THREAD

**Issue by IvanBurlaka** [quantroom-pro/pyrenko#5]

**Comment by lamres** [comment]
@IvanBurlaka
Hi Ivan!
This is a good question. It depends on you optimization approach. Any undefined parameter is a goal for optimization. You can implement some sort of walk-forward optimization and tune the hyperparameters. The frequency of recalculation is one of the hyperparameters. The another ones could be the length of history, the initial range of possible brick size, and so on. The global goal of WFA is defining all these undefined and important things.
